spring:
  application:
    name: api-gateway

  profiles:
    active: local

  main:
    web-application-type: reactive

  cloud:
    gateway:
      routes:
        - id: employee-service
          uri: lb://EMPLOYEE-SERVICE
          predicates:
            - Path=/api/v1/employee/**

        - id: company-service
          uri: lb://COMPANY-SERVICE
          predicates:
            - Path=/api/v1/company/**

        - id: iam-service
          uri: lb://IAM-SERVICE
          predicates:
            - Path=/api/v1/iam/**

